# Generated by Django 4.2.4 on 2023-08-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categorys'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Service Image', 'verbose_name_plural': 'Service Images'},
        ),
    ]
