# Generated by Django 4.2.4 on 2023-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('TanaRiver', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('WestPokot', ' West Pokot'), ('Samburu', 'Samburu'), ('TransNzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi ', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu ', 'Kisumu'), ('HomaBay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], db_index=True, max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3'), ('Location 4', 'Location 4'), ('Location 5', 'Location 5')], db_index=True, max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_county',
            field=models.CharField(choices=[('Sub 1', 'Sub 1'), ('Sub 2', 'Sub 2'), ('Sub 3', 'Sub 3'), ('Sub 4', 'Sub 4'), ('Sub 5', 'Sub 5')], db_index=True, max_length=50, verbose_name='Subcounty'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_location',
            field=models.CharField(choices=[('Sub_loc 1', 'Sub_loc 1'), ('Sub_loc 2', 'Sub_loc 2'), ('Sub_loc 3', 'Sub_loc 3'), ('Sub_loc 4', 'Sub_loc 4'), ('Sub_loc 5', 'Sub_loc 5')], db_index=True, max_length=50, verbose_name='Sublocation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='village',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Village/Estate'),
        ),
    ]
