# Generated by Django 4.2.4 on 2023-09-06 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/profile.jpg', null=True, upload_to='profiles', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', ''])], verbose_name='Profile'),
        ),
    ]
