# Generated by Django 4.2.4 on 2023-09-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tell',
            new_name='phone_number',
        ),
    ]
