# Generated by Django 4.2.4 on 2023-09-13 06:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('description', models.TextField(max_length=250)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_category_user', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Produce Category',
                'verbose_name_plural': 'Produce Categoryies',
            },
        ),
        migrations.CreateModel(
            name='ProduceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produce.producecategory', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_tag_user', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('growth_way', models.CharField(choices=[('Strictly Organic', 'Strictly Organic'), ('Organic', 'Organic'), ('Any', 'Any'), ('Inorganic', 'Inorganic')], max_length=50, verbose_name='Way of Growth')),
                ('organic_description', ckeditor.fields.RichTextField(verbose_name='Description way of growth')),
                ('control_growth', models.CharField(choices=[('Full Control', 'Full Control'), ('Partial Control', 'Partial Control'), ('No Control', 'No Control')], max_length=50, verbose_name='Control growth')),
                ('growth_period', models.CharField(max_length=50, verbose_name='Period Of Growth')),
                ('growth_fertilizer', models.CharField(max_length=50, verbose_name='Types of fertilizer')),
                ('growth_pestcides', models.CharField(max_length=50, verbose_name='Pesticides')),
                ('control_description', ckeditor.fields.RichTextField(verbose_name='Description way of control')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produce.producecategory', verbose_name='Category')),
                ('tags', models.ManyToManyField(to='Produce.producetag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Produce',
                'verbose_name_plural': 'Produces',
            },
        ),
    ]
