# Generated by Django 4.2.4 on 2023-09-14 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_date', models.DateTimeField(auto_now_add=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_produce', to='Produce.produce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produce Bookmark',
                'verbose_name_plural': 'Produce Bookmarks',
            },
        ),
    ]
