# Generated by Django 4.2.4 on 2023-08-17 06:00

import ckeditor.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('period', models.CharField(max_length=50, verbose_name='Period Of Lease')),
                ('other_period', models.CharField(blank=True, max_length=50, verbose_name='Other')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LeasePeriod',
                'verbose_name_plural': 'LeasePeriods',
            },
        ),
        migrations.CreateModel(
            name='Shamba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(max_length=12, unique=True, verbose_name='Land Id')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('shamba_id', models.CharField(max_length=50, verbose_name='Proof Of Ownership')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('size', models.FloatField(verbose_name='Land Size')),
                ('climate', ckeditor.fields.RichTextField(verbose_name='Describe Region Climate')),
                ('previous_farming', ckeditor.fields.RichTextField(verbose_name='Previous Farming Activity')),
                ('water_source', ckeditor.fields.RichTextField(verbose_name='Sourcse of Water')),
                ('electricity_source', ckeditor.fields.RichTextField(verbose_name='Source of Electricity')),
                ('charge', models.IntegerField(verbose_name='Lease Charges')),
                ('existing_infrastructure', ckeditor.fields.RichTextField(verbose_name='Existing Infrastructure')),
                ('recommended_farming', ckeditor.fields.RichTextField(verbose_name='Recommended Farming')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('period_lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_period', to='Shamba.leaseperiod', verbose_name='Lease Period')),
            ],
            options={
                'verbose_name': 'Shamba',
                'verbose_name_plural': 'Shambas',
            },
        ),
    ]
