# Generated by Django 4.2.4 on 2023-08-19 05:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0002_rename_shamba_land'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name': 'Land', 'verbose_name_plural': 'Lands'},
        ),
        migrations.AddField(
            model_name='land',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('TanaRiver', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('WestPokot', ' West Pokot'), ('Samburu', 'Samburu'), ('TransNzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi ', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu ', 'Kisumu'), ('HomaBay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], default='nairobi', max_length=50, verbose_name='County'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='existing_machinery',
            field=ckeditor.fields.RichTextField(default='nairobi', verbose_name='Existing Machinery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='human_labour',
            field=ckeditor.fields.RichTextField(default='nairobi', verbose_name='Human Labour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='soil_type',
            field=ckeditor.fields.RichTextField(default='nairobi', verbose_name='Soil type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='sub_county',
            field=models.CharField(choices=[('Sub 1', 'Sub 1'), ('Sub 2', 'Sub 2'), ('Sub 3', 'Sub 3'), ('Sub 4', 'Sub 4'), ('Sub 5', 'Sub 5')], default='nairobi', max_length=50, verbose_name='Subcounty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='sub_location',
            field=models.CharField(choices=[('Sub_loc 1', 'Sub_loc 1'), ('Sub_loc 2', 'Sub_loc 2'), ('Sub_loc 3', 'Sub_loc 3'), ('Sub_loc 4', 'Sub_loc 4'), ('Sub_loc 5', 'Sub_loc 5')], default='nairobi', max_length=50, verbose_name='Sublocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='land',
            name='village',
            field=models.CharField(default='nairobi', max_length=50, verbose_name='Village/Estate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3'), ('Location 4', 'Location 4'), ('Location 5', 'Location 5')], max_length=50, verbose_name='Location'),
        ),
        migrations.CreateModel(
            name='LandImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='lands', verbose_name='Land Images')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_images', to='Shamba.land', verbose_name='')),
            ],
            options={
                'verbose_name': 'LandImages',
                'verbose_name_plural': 'LandImagess',
            },
        ),
    ]
