# Generated by Django 4.2.4 on 2023-08-19 05:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0003_alter_land_options_land_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
