# Generated by Django 4.2.4 on 2023-08-22 19:52

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0006_landcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landcategory',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='landcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='type'),
        ),
    ]
