# Generated by Django 4.2.4 on 2023-08-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0007_rename_name_landcategory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_category', to='Shamba.landcategory', verbose_name='Category'),
        ),
    ]
