# Generated by Django 4.2.4 on 2023-08-23 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shamba', '0009_alter_land_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_date', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_lands', to='Shamba.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BookmarkedLand',
                'verbose_name_plural': 'BookmarkedLands',
            },
        ),
    ]
