# Generated by Django 4.2.4 on 2023-08-24 05:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0010_bookmarkedland'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='location_coordinates',
        ),
        migrations.AddField(
            model_name='land',
            name='zipcode',
            field=models.CharField(default='100100', max_length=50, verbose_name='Zipcode'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LandCoordiates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shamba.land', verbose_name='')),
            ],
            options={
                'verbose_name': 'LandCoordiates',
                'verbose_name_plural': 'LandCoordiatess',
            },
        ),
    ]
