# Generated by Django 4.2.4 on 2023-08-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0011_remove_land_location_coordinates_land_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landcoordiates',
            old_name='update',
            new_name='updated',
        ),
    ]
