# Generated by Django 4.2.4 on 2023-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0012_rename_update_landcoordiates_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='title',
            field=models.CharField(default='Rich fertile 1 acre', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
