# Generated by Django 4.2.4 on 2023-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0014_landtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='tags',
            field=models.ManyToManyField(to='Shamba.landtag', verbose_name='Tags'),
        ),
    ]
