# Generated by Django 4.2.4 on 2023-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shamba', '0015_land_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='size_units',
            field=models.CharField(choices=[('Acre', 'Acre'), ('Hectares', 'Hectares')], default='Acres', max_length=50, verbose_name='Size Unit'),
            preserve_default=False,
        ),
    ]
