# Generated by Django 4.2.4 on 2023-09-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolimage',
            options={'verbose_name': 'Tool Image', 'verbose_name_plural': 'Tool Images'},
        ),
        migrations.RenameField(
            model_name='toolimage',
            old_name='tools',
            new_name='tool',
        ),
    ]
