# Generated by Django 4.2.4 on 2023-08-25 05:57

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tools.tool', verbose_name='Tags')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='Tools.TaggedTools', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
