# Generated by Django 4.2.4 on 2023-08-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tools', '0002_taggedtools_tool_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tool_category_user', to=settings.AUTH_USER_MODEL, verbose_name=''),
            preserve_default=False,
        ),
    ]
