# Generated by Django 4.2.4 on 2023-09-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0002_alter_toolimage_options_rename_tools_toolimage_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolimage',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_images', to='Tools.tool', verbose_name=''),
        ),
    ]
