# Generated by Django 4.2.4 on 2023-08-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0003_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedtools',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tools.tool'),
        ),
    ]
