# Generated by Django 4.2.4 on 2023-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0003_alter_toolimage_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
