# Generated by Django 4.2.4 on 2023-08-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0006_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='category',
        ),
    ]
