# Generated by Django 4.2.4 on 2023-09-16 04:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produce', '0002_producebookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge', models.IntegerField(verbose_name='Charge')),
                ('reasons', ckeditor.fields.RichTextField(verbose_name='Reasons For you charge')),
                ('services', ckeditor.fields.RichTextField(verbose_name='Other secondary Services ')),
                ('status', models.CharField(default='PENDING', max_length=50, verbose_name='')),
                ('approved_cancelled_time', models.DateTimeField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produce.produce', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
