# Generated by Django 4.2.4 on 2023-09-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='approved_cancelled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
    ]
