# Generated by Django 4.2.4 on 2023-09-16 04:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0002_alter_bid_approved_cancelled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='services',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Other secondary Services '),
        ),
    ]
